repository_type: pipeline
nf_core_version: "2.14.1"
lint:
  actions_ci: False
  files_exist:
    - conf/igenomes.config
  files_unchanged:
    - .gitattributes
    - assets/nf-core-spatialtranscriptomics_logo_light.png
    - docs/images/nf-core-spatialtranscriptomics_logo_light.png
    - docs/images/nf-core-spatialtranscriptomics_logo_dark.png
