channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python packages
  - bbknn=1.5.1
  - jinja2=3.1.1
  - leidenalg=0.8.9
  - matplotlib=3.5.1
  - scikit-learn=1.0.2
  - scanorama=1.7.1
  - scanpy=1.8.2
  - scipy=1.8.0
  - seaborn=0.11.2
  - umap-learn=0.5.2

  # Pip packages
  - pip=22.0.04
  - pip:
      - spatialde=1.1.3

  # R packages
  - bioconductor-bluster=1.4.0
  - bioconductor-bayesspace=1.4.1
  - bioconductor-deseq2=1.34.0
  - bioconductor-scran=1.22.1
  - bioconductor-singlecellexperiment=1.16.0
  - bioconductor-spatialde=1.0.0
  - bioconductor-spatialexperiment=1.4.0
  - r-argparse=2.1.3
  - r-corrplot=0.92
  - r-devtools=2.4.3
  - r-fastmap=1.1.0
  - r-ggcorrplot=0.1.3
  - r-gt=0.4.0
  - r-hdf5r=1.3.5
  - r-rsvd=1.0.5
  - r-reticulate=1.24
  - r-seurat=4.1.0
  - r-tidyverse=1.3.1
