channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python packages
  - bbknn=1.5.1
  - leidenalg=0.8.9
  - matplotlib=3.5.1
  - scikit-learn=1.0.2
  - scanorama=1.7.1
  - scanpy=1.8.2
  - scipy=1.8.0
  - seaborn=0.11.2
  - umap-learn=0.5.2
  - papermill=2.3.4
  - jupyter=1.0.0
