channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - leidenalg=0.9.1
  - papermill=2.3.4
  - pip=23.0.1
  - scanpy=1.9.8
  - seaborn=0.12.2
  - pip:
      - SpatialDE==1.1.3
